apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fractal-accounts.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "fractal-accounts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "fractal-accounts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: auth-svc
          image: "{{ .Values.image.repository }}/auth-svc:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: fractal-secret
                  key: db-url
          resources: {{- toYaml .Values.resources | nindent 12 }}
